name: GitHub Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-08-08
      - name: Build doc
        run: cargo doc --no-deps
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}